spring.application.name=loc_mns

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto = create

spring.sql.init.platform = init
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode = always

# évite un hashing trop tôt (avant validation -> pb contrôle longueur password)
spring.jpa.properties.jakarta.persistence.validation.mode=none